- name: get distrib facts
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - 'status-{{ ansible_distribution }}.yml'
      skip: true
  run_once: yes

- name: get running {{ mariadb_process_name }}
  command: pgrep {{ mariadb_process_name }}
  register: mypids
  check_mode: False
  failed_when: False
  changed_when: False

- name: get current config
  shell: "set -o pipefail && /usr/local/libexec/{{ mariadb_process_name }} --print-defaults | sed 's/--/\\n/g;' | sed 's/=\\([0-9]\\) $/: \\1/; s/=\\(.*\\) $/: \"\\1\"/;' | grep -v '^/' | grep -v '^$'"
  register: mysqld_config
  check_mode: False
  failed_when: False
  changed_when: False
  
- name: get mariadb status vars
  shell: "set -o pipefail && mysql -e \"SHOW STATUS LIKE 'wsrep_%';\" -s -N | sed 's/\\t\\([0-9]\\{1,\\}\\)$/: \\1/; s/\\t\\(.*\\)$/: \"\\1\"/'"
  register: mysql_status
  check_mode: False
  failed_when: False
  changed_when: False

- name: register status
  set_fact:
    mariadb_current_status: '{% if mysql_status.rc == 0 %}{{ mysql_status.stdout | from_yaml }}{% else %}{}{% endif %}'
    mariadb_current_config: '{% if mysqld_config.rc == 0 %}{{ mysql_status.stdout | from_yaml }}{% else %}{}{% endif %}'
    mariadb_is_running: '{% if mypids.rc == 0 %}True{% else %}False{% endif %}'

- name: facts
  set_fact:
    do_mariadb_install: '{% if not do_upgrade_mariadb and not mariadb_relayout_zfs and mariadb_is_running %}False{% else %}True{% endif %}'
    galera_is_running: '{% if mariadb_current_status["wsrep_cluster_size"] | default(0) > 1 %}True{% else %}False{% endif %}'

- name: show status
  debug:
    msg: |
      mariadb_is_running: {{ mariadb_is_running }}
      galera_is_running: {{ galera_is_running }}
