---
- name: rc.conf
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}='
  with_items:
    - { key: mysql_enable, value: "YES" }
    - { key: mysql_dbdir, value: '{{ mariadb_basedir }}' }

- name: get zfs facts
  zfs_facts:
    dataset: '{{ mariadb_zfs_base }}'
  register: zfs_base_fact
  when: mariadb_zfs_base | length > 0
  ignore_errors: True

- name: stop mysql pour zfs
  service:
    name: '{{ mariadb_service }}'
    state: stopped
  when: mariadb_zfs_base | length > 0 and ( zfs_base_fact.failed or not ansible_zfs_datasets[0].mountpoint == mariadb_basedir )

- name: move old dir
  command: 'mv {{ mariadb_basedir }} {{ mariadb_basedir }}.orig'
  when: mariadb_zfs_base | length > 0 and ( zfs_base_fact.failed or not ansible_zfs_datasets[0].mountpoint == mariadb_basedir )
  failed_when: False

- name: 'zfs {{ mariadb_zfs_base }}'
  zfs:
    name: '{{ mariadb_zfs_base }}'
    state: present
    extra_zfs_properties:
      mountpoint: '{{ mariadb_basedir }}'
      recordsize: 16K
  when: mariadb_zfs_base | length > 0 and ( zfs_base_fact.failed or not ansible_zfs_datasets[0].mountpoint == mariadb_basedir )
  register: zfs_base

- name: zfs innodb-logs
  zfs:
    name: '{{ mariadb_zfs_base }}/innodb-logs'
    state: present
    extra_zfs_properties:
      mountpoint: '{{ mariadb_basedir }}/innodb-logs'
      recordsize: 128K
      sync: 'disabled'
  register: zfs_innodb_logdir
  when: zfs_base.changed | default(False)

- name: move innodb_logs
  shell: 'mv {{ mariadb_basedir }}/ib_logfile* {{ mariadb_basedir }}/innodb-logs/'
  failed_when: False
  when: zfs_innodb_logdir.changed | default(False)

- name: enable zfs
  service:
    name: zfs
    enabled: yes
  when: mariadb_zfs_base | length > 0

- name: login.conf
  blockinfile:
    dest: /etc/login.conf
    content: |
      mysql:\
        :lang=fr_FR.UTF-8:\
        :charset=UTF-8:\
        :tc=daemon:

    marker: '# {mark} mariadb by ansible block'
    backup: yes
  register: loginconf

- name: cap_mkdb
  command: cap_mkbd /etc/login.conf
  when: loginconf.changed | default(False)

- name: install mariadb
  pkgng:
    name:
      - 'mariadb{{ mariadb_version | regex_replace("[^0-9]","") }}-server'
      - 'py{{ ansible_python_version | regex_replace("([2-3])\.([0-9]*)\..*$","\1\2") }}-pymysql'
    state: present
  register: install_mariadb

- name: newsyslog
  copy:
    force: no
    dest: /usr/local/etc/newsyslog.conf.d/mariadb.conf
    content: |
      {{ mariadb_logdir }}/*.log  {{ mariadb_owner }}:{{ mariadb_group }}  640 7 1000  @T00  G {{ mariadb_basedir }}/{{ ansible_fqdn }}.pid
