---
- name: rc.conf
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}='
  with_items:
    - { key: mysql_enable, value: "YES" }
    - { key: mysql_dbdir, value: '{{ mariadb_basedir }}' }

- name: zfs props
  zfs:
    name: '{{ mariadb_zfs_base }}'
    state: present
    extra_zfs_properties:
      mountpoint: '{{ mariadb_basedir }}'
      recordsize: 16K
  when: mariadb_zfs_base != ""

- name: enable zfs
  service:
    name: zfs
    enabled: yes
  when: mariadb_zfs_base != ""

- name: install mariadb
  pkgng:
    name:
      - 'mariadb{{ mariadb_version | regex_replace("[^0-9]","") }}-server'
      - 'py{{ ansible_python_version | regex_replace("([2-3])\.([0-9]*)\..*$","\1\2") }}-MySQLdb'
    state: present
  register: install_mariadb

- name: newsyslog
  copy:
    force: no
    dest: /usr/local/etc/newsyslog.conf.d/mariadb.conf
    content: |
      {{ mariadb_logdir }}/*.log  root:{{ mariadb_group }}  640 7 1000  @T00  G


