---
- name: install
  include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: '{{ mariadb_basedir }}/my.cnf'
  template:
    src: my.cnf.j2
    dest: '{{ mariadb_basedir }}/my.cnf'
    mode: '0644'
    force: no

- name: log dir
  file:
    dest: '{{ mariadb_logdir }}'
    state: directory
    mode: '0750'
    owner: '{{ mariadb_owner }}'
    group: '{{ mariadb_group }}'

- name: dbdir
  file:
    dest: '{{ mariadb_basedir }}'
    state: directory
    owner: '{{ mariadb_owner }}'
    group: '{{ mariadb_group }}'
    mode: 'ug+rwX,o-rwx'
    recurse: yes

- name: first install
  block:
    - name: start mariadb server
      service:
        name: '{{ mariadb_service }}'
        state: started
        enabled: yes
    - name: no test db
      mysql_db:
        login_unix_socket: '{{ mariadb_socket }}'
        name: test
        state: absent
    - name: no empty mysql user for localhost
      mysql_user:
        login_unix_socket: '{{ mariadb_socket }}'
        name: ''
        host: localhost
        state: absent
    - name: no empty mysql user for any host
      mysql_user:
        login_unix_socket: '{{ mariadb_socket }}'
        name: ''
        host_all: yes
        state: absent
    - name: no root on 127.0.0.1
      mysql_user:
        login_unix_socket: '{{ mariadb_socket }}'
        name: 'root'
        host: '127.0.0.1'
        state: absent
    - name: no root on ::1
      mysql_user:
        login_unix_socket: '{{ mariadb_socket }}'
        name: 'root'
        host: '::1'
        state: absent
  when: install_mariadb.changed

- name: 'default admin {{ mariadb_admin_user }}'
  mysql_user:
    name: '{{ mariadb_admin_user }}'
    password: '{{ mariadb_admin_password }}'
    update_password: on_create
    login_unix_socket: '{{ mariadb_socket | default(omit) }}'
    host: '%'
    priv: '*.*:ALL,GRANT'
    state: present
  when: 'mariadb_admin_user | length > 0 and mariadb_admin_password | length > 0'

- name: root pass
  mysql_user:
    login_unix_socket: '{{ mariadb_socket }}'
    name: root
    password: '{{ mariadb_root_password }}'
    host: localhost
    append_privs: yes
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: yes
    state: present

- name: /root/.my.cnf
  copy:
    dest: /root/.my.cnf
    mode: '0600'
    backup: yes
    content: |
      [mysql]
      user=root
      {% if mariadb_root_password | length > 0 %}password={{ mariadb_root_password }}{% endif %}

      [mysqladmin]
      user=root
      {% if mariadb_root_password | length > 0 %}password={{ mariadb_root_password }}{% endif %}

- name: local facts
  copy:
    src: my_dbs.fact
    dest: '{{ etcprefix }}/etc/ansible/facts.d/my_dbs.fact'
    mode: '0550'

- name: new users
  mysql_user:
    login_unix_socket: '{{ mariadb_socket }}'
    name: '{{ item.name }}'
    priv: '{{ item.priv | default("*.*:USAGE") }}'
    host: '{{ item.host | default("localhost") }}'
    password: '{{ item.password | default(item.name | hash("sha256")) }}'
    state: present
  with_items: '{{ mariadb_users | union(mariadb_maintenance_users) }}'

- name: new dbs
  mysql_db:
    login_unix_socket: '{{ mariadb_socket }}'
    name: '{{ item.name }}'
    state: present
  with_items:
    - '{{ mariadb_dbs }}'
  when: 'mariadb_dbs | count > 0'
