---
# handlers file for criecm.mariadb
- name: reload syslogd
  service:
    name: syslogd
    state: reloaded

- name: restart mariadb
  service:
    name: '{{ mariadb_service }}'
    state: restarted
  when: not mariadb_no_restart | default(False) or not mypids

- name: mysql_upgrade
  command: 'mariadb-upgrade'

- name: reload inetd
  service:
    name: inetd
    state: reloaded

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
